cluster.name: my-application
node.name: node-ub2
network.host: 0.0.0.0
network.publish_host: 192.168.1.138
http.port: 9200
discovery.zen.ping.unicast.hosts: ["192.168.1.116"]
discovery.zen.minimum_master_nodes: 1